baseURL = "http://hellsgate.co.ke/"
languageCode = "en-us'"
title = "Hell's Gate National Park"
theme = "hellsgate"

[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.133.1"  # Replace with your Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"


